import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Sample Research Report | Typhoon Deep Research Demo',
    description: 'View a sample research report generated by Typhoon AI. See how our advanced AI creates comprehensive, citation-backed research reports on complex topics.',
    keywords: ['sample research report', 'AI-generated report', 'Typhoon demo report', 'example AI research', 'citation-backed report'],
    openGraph: {
        title: 'Sample Research Report | Typhoon Deep Research Demo',
        description: 'View a sample research report generated by Typhoon AI. See how our advanced AI creates comprehensive, citation-backed research reports on complex topics.',
    },
    twitter: {
        title: 'Sample Research Report | Typhoon Deep Research Demo',
        description: 'View a sample research report generated by Typhoon AI. See how our advanced AI creates comprehensive, citation-backed research reports on complex topics.',
    }
}; 